### ISSUE TITLE
Cannot add UseContextMenu to MauiProgram.cs

### ISSUE THREAD

**Issue by ckrutsinger** [jerry08/Plugin.ContextMenuContainer#1]
Per Readme, I add `using Plugin.ContextMenuContainer` and the `.UseContextMenu()` to the `builder` in MauiProgram.cs, but I get an error message that UseContextMenu() does not exist.

![image](https://github.com/jerry08/Plugin.ContextMenuContainer/assets/49876709/8c320be1-4fe0-4d81-b49b-87df6314e9cd)

**Comment by ckrutsinger** [comment]
Looking through your code, I see only ConfigureContextMenuContainer() as an extension to MauiAppBuilder. Is the Readme out of date?

**Comment by jerry08** [comment]
Yes, it is. Sorry, I forgot to update the Readme. You can use `.ConfigureContextMenuContainer()`
