### ISSUE TITLE
Context menu not appearing on iOS

### ISSUE THREAD

**Issue by ckrutsinger** [jerry08/Plugin.ContextMenuContainer#2]
Plugin.ContextMenuContainer v1.0.6

Added context menu to main page.
Running on Android, tapping content will bring up context menu.
Running on iOS, tapping on content does nothing.

Expected content menu to appear.

Example project with issue at [https://github.com/ckrutsinger/MauiContextMenuPlugin.git](https://github.com/ckrutsinger/MauiContextMenuPlugin.git)

**Comment by jerry08** [comment]
You have to make your repository public so I can see it. But I think I already know what may be your problem. On iOS, the context menu content must be a `Button` or `ImageButton` if you want it to open when tapped. Otherwise, long-pressing it will open the menu.

https://developer.apple.com/documentation/uikit/uicontrol/3601223-showsmenuasprimaryaction

For iOS as shown above, `showsMenuAsPrimaryAction` only applies to buttons, unfortunately.

**Comment by ckrutsinger** [comment]
Thanks, @jerry08.  Long press is working. So if I change my Label to a Button, will it act the same on both Android and iOS?

**Comment by jerry08** [comment]
Yes, that is correct.

**Comment by ckrutsinger** [comment]
@jerry08 This button still requires a long press to open on iOS. Did I miss a setting?

``` 
            <cm:ContextMenuContainer x:Name="ActionsInline" >
                <cm:ContextMenuContainer.MenuItems>
                    <cm:ContextMenuItem          
                        Text="{x:Static localize:Lang.MobileServiceAdvisor}"
                        Icon="{AppThemeBinding Light=toolsblack, Dark=toolswhite}"
                        Command="{Binding ChangeWorkflowCommand}" 
                        CommandParameter="MobileServiceAdvisor" />
                    <cm:ContextMenuItem 
                        Text="{x:Static localize:Lang.TireMaintainer}"
                        Icon="{AppThemeBinding Light=tireiconblack, Dark=tireiconwhite}"
                        Command="{Binding ChangeWorkflowCommand}"  
                        CommandParameter="TireMaintainer" />
                </cm:ContextMenuContainer.MenuItems>
                <cm:ContextMenuContainer.Content  >
                    <Button Text="{Binding Workflow}" 
                           FontSize="Medium"
                           Style="{StaticResource ModernConstructiveButton}"
                           Margin="10,3,3,3"
                           HorizontalOptions="Start"
                           />
                </cm:ContextMenuContainer.Content>
            </cm:ContextMenuContainer>
```

Also tried with:

```
            <cm:ContextMenuContainer x:Name="ActionsInline" ShowOnClick="True">
```

and still not responding to tap, only long press.
