### ISSUE TITLE
Support for net8.0 target

### ISSUE THREAD

**Issue by Paulinho00** [jerry08/Plugin.ContextMenuContainer#5]
Hi,
Currently, your package is only available for four targets:

- net8.0-android34.0
- net8.0-ios17.2
- net8.0-maccatalyst17.2
- net8.0-windows10.0.19041

To build a test project, for example, you have to build an app for .net8.0, which is impossible if your package is used. Can you add support for target .net8.0? In previous versions, your package supported .net6.0, so it seems like it should not be a big change.

**Comment by jerry08** [comment]
Sure. Should I also migrate to .net9.0?

**Comment by Paulinho00** [comment]
We don't need .net9.0, at least for now, we need .net8.0 specifically. Shortly we would probably upgrade our project but having .net8.0 is a more urgent need at the moment

**Comment by jerry08** [comment]
A new version is now available.
